### ISSUE TITLE
Installation: make padsc_comp fails 

### ISSUE THREAD

**Issue by gapag** [padsproj/pads#1]
On Ubuntu 14.04, 64 bit machine.
Following the README, 

make padsc_comp

pads/padsc/comp/build-exec-45.sml tries to write in pads/lib.
(in pads/padsc/comp/main.sml, line 462 and below )

Such directory does not exist and is not created automatically, making the installation fail.

Preconditions: 
a) be root
b) the $PADS_HOME directory tree with the most liberal permissions all the way down.
c) freshly checked out pads repository
1. changed permissions all the way down with chmod 777 pads -R
2. set correctly $PADS_HOME and $SML as specified in README
3. ran . /home/gapag/devel/pads/scripts/Q_DO_SETENV.sh
4. make ast_lib , creating
   - ./ast-ast/arch/linux.i386-64/src/lib/libast/libast.a
   - ./ast-ast/arch/linux.i386-64/lib/libast.a
5. make padsc_lib , creating
   - ./ast-ast/arch/linux.i386-64/lib/libpads-g.a
   - ./ast-ast/arch/linux.i386-64/lib/libpads.a
   - ./padsc/libpads/linux.i386-64/libpads-g.a
   - ./padsc/libpads/linux.i386-64/libpads.a
6. make test_libpads , output: http://pastebin.com/062fkE4T

seem to go fine. Until here no pads/lib directory has been created,
but  libast.a and libpads.a have been created and tests seem to succeed.

7 . make padsc_comp 
results in a writing error: http://pastebin.com/g1RKundm

**Comment by gapag** [comment]
If one substitutes 7. with 

7a. Created pads/lib manually and set chmod 777 pads/lib -R.
When issuing
make padsc_comp
the script runs correctly and the result is the 4.6 MB file
pads/lib/padsc.x86-linux.

No error message is issued, see http://pastebin.com/h5En7buR

**Comment by gapag** [comment]
Nevertheless, the tests

8 . make test_comp, output http://pastebin.com/EbhL7S5Y

do not work. 

Notably, the standard output of make test_comp seems not to reflect the problems that the standard error manifests, that is, it says tests went fine (I suppose):

> Number of regression tests with differences: 0

Maybe .p files included have an older syntax than the one that the current pads compiler recognizes?

**Comment by athleens** [comment]
The file format for .p files hasn’t changed, so that’s not the issue.

It would be good to check to see if the compiler has indeed been built.

Kathleen

**Comment by gapag** [comment]
I do not know how to check. Which files should I look for? 
I can tell what output the scripts/padsc returns me:
**When pads/lib is manually created**
The output of make padsc_comp (http://pastebin.com/h5En7buR) does not state explicitly success nor failure. The pads/lib/padsc.x86-linux file is created.
Executing

> $ ./scripts/padsc  --help

one gets

> Help for the padsc wrapper script:
> 1. Retargeting of generated files.
>       PRECONDITIONS for retargeting are:
>           + all .p files are in the same dir P
>           + an explicit -p option is used
>       When these conditions are met, the following retargeting
>       rules are applied, with rule A having higher precedence:
>           A. if P/gen is a directory, it is used as the target dir
>           B. if P/../gen is a directory, it is used as the target dir
> 2. The script needs to determine , the location of the
>     PADS installation, so that it can find /padsc/include
>     and /padsc/lib.  If environment variable PADS_HOME is
>     not set, or if the path to the script does not help us find
>     pads_home, the script fails and reports an error.

and then

> PADS Compiler version 2.01
> padsc  [-wnone] [-xsnone] [-anone] [-x] [-hist] [-cluster] [-r <string>] [-b <string>] [-I <string> ...] [-D <string> ...] [-U <string> ...] [-t] [--help] file...
> -wnone  suppress write function generation
> -xsnone suppress XSchema generation
> -anone  suppress accumulator generation
> -x  output Galax Data API
> -hist   output histogram functions
> -cluster    output cluster functions
> -r  output directory
> -b  add base type table
> -I  augment include path
> -D  add definition
> -U  remove definition
> -t  trace system commands
> 
> File extensions:
> .p  PADS files

**When make_padsc_comp is executed without creating manually the directory pads/lib**
instead of showing version of PADS and its command line options, the same command shows the same preamble about retargeting followed by the error

> /usr/lib/smlnj/bin/sml: Fatal error -- unable to open heap image "/home/gapag/devel/pads/lib/padsc"

instead of

> PADS Compiler version 2.01
> ...
> File extensions:
> .p  PADS files

**Comment by gapag** [comment]
And, running the compiler on a file gives:

> $ ./scripts/padsc padsc/examples/p/pendian.p 
> 
> Auto-selecting target dir /home/gapag/devel/pads/padsc/examples/gen
> 
> "/home/gapag/devel/pads/padsc/include/pads.h":1278.75-82: padsc error: syntax error: replacing  ID with  TYPE_NAME
> Likely cause: missing typedef declaration.
> 
> "/home/gapag/devel/pads/padsc/include/pads.h":1290.37-44: padsc error: syntax error: replacing  ID with  TYPE_NAME
> Likely cause: missing typedef declaration.
> 
> "/home/gapag/devel/pads/padsc/include/pads-internal.h":1956.63-70: padsc error: syntax error: replacing  ID with  TYPE_NAME
> Likely cause: missing typedef declaration.
> 
> "???": padsc warning: additional errors suppressed.
> "???": padsc warning: additional warnings suppressed.

which is the same error that one can read in the make test_comp output: http://pastebin.com/EbhL7S5Y

**Comment by athleens** [comment]
Sorry for the long delay in responding.  I've been swamped with other things.

The image for the compiler should go in 
  $PADS_HOME/lib/padsc.ARCH-OPSYS
where ARCH and OPSYS are determined by your machine.

It looks like your sml compiler can't write to that location for some reason.

**Comment by gapag** [comment]
No problem at all for the delay.

It is weird because the permissions are the most liberal possible.
I even tried to run the whole process as super user, but I get the same outcome.
I am using

> Standard ML of New Jersey v110.76 [built: Tue Oct 22 14:04:11 2013]

and I installed it through the ubuntu package manager.
**Q: Might it be that I lack some SML components used in the installation scripts?**

As I mentioned before, if I manually create $PADS_HOME/lib/ then padsc.x86-linux gets created but no message tells me if everything went fine; running the compiler results in errors mentioning as likely cause "missing typedef declaration"  (logs linked in last two messages).

**Q: Does this likely mean that not everything has been compiled?**

**Comment by athleens** [comment]
You can tell if the pads runtime system installed properly by running

> gmake test_libpads
> as described in the file $PADS_HOME/README.  

It looks like creating the directory solves the problem compiling the pads compiler.  

So that leaves the problem with the type error messages.  

Can you let me know what is on the following lines of your pads.h file?

"/home/gapag/devel/pads/padsc/include/pads.h":1278.75-82: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

"/home/gapag/devel/pads/padsc/include/pads.h":1290.37-44: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

"/home/gapag/devel/pads/padsc/include/pads-internal.h":1956.63-70: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

The padsc compiler is having to parse the C header file, and C header files are less standard than one might wish.  I suspect the problem is with the type "va_list" being in the prototype of the functions on those lines.  We've sorted out this problem before, but I'll have to remember how.

**Comment by gapag** [comment]
Find below the excerpts you asked about and the links to the whole files. I beg your pardon, I should have provided this information earlier.
Here are the individual lines and files:

**in pads.h**
`/* Pinv_val_fn: type of a pointer to an invalid val function */`

``` C
/*line 1278:*/ typedef Perror_t (*Pinv_val_fn)(P_t *pads, void *pd_void, void *val_void, va_list type_args);
```

[...]

``` C
/*line 1287:*//* Pfmt_fn: type of a pointer to a fmt function */
typedef ssize_t (*Pfmt_fn)(P_t *pads, Pbyte *buf, size_t buf_len,
               int *buf_full, int *requestedOut, char const *delims,
/*line 1290:*/`    void *m, void  *pd, void *rep, va_list type_args);
```

[...]

``` C
```

**in pads-internal.h:**

``` C
/*line 1956:*/int sfvsnscanf (const char *s, size_t slen, const char *form, va_list args);
```

For your convenience, please find the whole files:
[pads.h.txt](https://github.com/padsproj/pads/files/33678/pads.h.txt)
[pads-internal.h.txt](https://github.com/padsproj/pads/files/33684/pads-internal.h.txt)

**Comment by gapag** [comment]
I suppose it is the type `va_list`  that  the compiler has problems with.
Out of curiosity, if this might help, I issued from PADS_HOME:

``` sh
PADS_HOME $ rgrep va_list . | grep typedef
```

and got:

```
./ast-ast/arch/linux.i386-64/include/pads.h:typedef Perror_t (*Pinv_val_fn)(P_t *pads, void *pd_void, void *val_void, va_list type_args);
./padsc/bugs/cygwinInfo/stdarg.h:typedef __builtin_va_list __gnuc_va_list;
./padsc/bugs/cygwinInfo/stdarg.h:typedef __gnuc_va_list va_list;
./padsc/bugs/cygwinInfo/stdarg.h:typedef __gnuc_va_list va_list;
./padsc/include/ckit-first.h:typedef void * __builtin_va_list;
./padsc/include/pads.h:typedef Perror_t (*Pinv_val_fn)(P_t *pads, void *pd_void, void *val_void, va_list type_args);
./padsc/include/ckit-replace.h://typedef struct{int x;} va_list;
./padsc/include/ckit-replace.h:// typedef _ast_va_list va_list;
./padsc/include/pads.h.txt:typedef Perror_t (*Pinv_val_fn)(P_t *pads, void *pd_void, void *val_void, va_list type_args);
```

**Comment by athleens** [comment]
There's a C-preprocessor flag __LINUX_PREPROCESSOR_FIXES that is designed to address this problem.   Try invoking the padsc compiler with the -D __LINUX_PREPROCESSOR_FIXES option.

**Comment by gapag** [comment]
No, unfortunately I get the same error as before. I tried even 
`-D__LINUX_PREPROCESSOR_FIXES`  (without space)
and
`-DHAVE_VA_LIST` (with and without space after -D)
as I found them both in the `padsc` script, but **running the script with the variable `$dbg = 1` showed that the script anyway appends such two strings in the command it issues to run pads.**

```
sudo ./scripts/padsc ../padsc/examples/p/pendian.p
[...]
exec /usr/bin/sml @SMLload=/home/gapag/devel/pads/lib/padsc /home/gapag/devel/pads 
  /usr/bin/cc ../padsc/examples/p/pendian.p 
  -U__GNUC__ 
  -D__LINUX_PREPROCESSOR_FIXES 
  -DHAVE_VA_LIST 
  -I /home/gapag/devel/pads/padsc/include 
  -I /home/gapag/devel/pads/ast-ast/arch/linux.i386-64/include/ast 
```

(I reformatted the output to make it more readable)

**Comment by gapag** [comment]
There is this detail, which I  guess is irrelevant, but I'd like to share:
the `padsc` script determines the architecture by running 

``` perl
my $ast_arch = `$pads_home/ast-ast/bin/package.cvs` || "";
```

The script `package.cvs` determines the architecture as linux.i386-64 (mine is x86-64). 
The compilation of the AST library has indeed created artifacts under the directory
`$PADS_HOME/ast-ast/arch/linux.i386-64`
1) I am not sure that `package.cvs` can ever output `linux.x86_64`  which is my architecture, that appears correct in the name of the padsc compiler `$PADS_HOME/libs/padsc.x86-linux`
2) I am **quite** sure that the `padsc` script executes the same, modulo the value of the `$ast_arch` variable, which anyway makes all paths in which its value is used always point to existing directories/files.

**Does this probably show that there is a problem in my AST library compilation, or is it not something to worry about?** 
I am worried about this because the `padsc` script makes the following check:

``` perl
if ($ast_arch =~ /linux.x86_64/){
    $lda = $lda . " -DHAVE_VA_LIST";
}

if ($ast_arch =~ /linux.i386-64/){
    $lda = $lda . " -DHAVE_VA_LIST";
}
```

which makes me suspect that I get the wrong output from `package.cvs`, therefore something might be "wrong" with my AST library.

**Comment by athleens** [comment]
This may be a problem, but I’d guess it would manifest more in linking than in compiling pads source files. 

Can you check to see if the lines in ckit-first.h protected by the flag __LINUX_PREPROCESSOR_FIXES are getting included in the file passed to the padsc compiler?    

Kathleen

**Comment by gapag** [comment]
> Can you check to see if the lines in ckit-first.h protected by the flag __LINUX_PREPROCESSOR_FIXES 
> are getting included in the file passed to the padsc compiler? 

If you mean if the `.p` layout file I am passing to the padsc compiler contains the protected code in or any reference to `ckit-first.h`, then the answer is no:

`$PADS_HOME/padsc/examples/p/simple.p`'s contents:

``` C
Pstruct foo{
  int f;
  int j;
};
```

`ckit-first.h`'s contents:

``` C
/* ================================================================================ */
/* XXX THESE ARE REQUIRED FOR CKIT ON REDHAT LINUX 7.3 (AND MAYBE OTHERS) */

#ifdef __LINUX_PREPROCESSOR_FIXES
typedef void * __builtin_va_list;
#define __THROW
/* extern int ftruncate (int __fd, long int __length) ; */

#endif
```

Adding either of 
`typedef void * __builtin_va_list;`
`#include "ckit-first.h"`
at the beginning of `simple.p` does not seem to have any effect on the output, which is invariably

```
exec /usr/bin/sml @SMLload=/home/gapag/devel/pads/lib/padsc /home/gapag/devel/pads /usr/bin/cc -r /home/gapag/devel/pads/padsc/examples/gen padsc/examples/p/simple.p -U__GNUC__ -D__LINUX_PREPROCESSOR_FIXES -DHAVE_VA_LIST -I /home/gapag/devel/pads/padsc/include -I /home/gapag/devel/pads/ast-ast/arch/linux.i386-64/include/ast 

"/home/gapag/devel/pads/padsc/include/pads.h":1278.75-82: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

"/home/gapag/devel/pads/padsc/include/pads.h":1290.37-44: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

"/home/gapag/devel/pads/padsc/include/pads-internal.h":1956.63-70: padsc error: syntax error: replacing  ID with  TYPE_NAME
Likely cause: missing typedef declaration.

"/home/gapag/devel/pads/padsc/examples/p/simple.p":2.57-64: padsc error: syntax error: replacing  PSTRUCT with  SEMICOLON
Likely cause: missing typedef declaration.

"???": padsc warning: additional errors suppressed.
"???": padsc warning: additional warnings suppressed.
```

**Comment by gapag** [comment]
Furthermore, some greps I did out of curiosity:

**`$ rgrep "ckit-first.h" .`**

```
Binary file ./.git/index matches
./padsc/comp/main.sml:            val includePrefix = ("#include <ckit-first.h>\n"^
Binary file ./padsc/comp/.cm/x86-unix/main.sml matches
Binary file ./lib/padsc.x86-linux matches
```

**`$ rgrep "__LINUX_PREPROCESSOR_FIXES" .`**

```
./scripts/padsc:    $lda = "-D__LINUX_PREPROCESSOR_FIXES";
./scripts/padsc:        print "I set -D__LINUX_PREPROCESSOR_FIXES";   
./padsc/include/ckit-first.h:#ifdef __LINUX_PREPROCESSOR_FIXES
```

**Comment by athleens** [comment]
Submitted a fix to ckit-first.h that fixes this bug.
